### ISSUE TITLE
Scaffold Flask Project

### ISSUE THREAD

**Issue by hansenreid** [paulfiesel/TD2-Stats#1]
We need to initialize a new Flask project in the repo. It should be in the `backend` folder. Instructions for installing Flask can be found [here](https://flask.palletsprojects.com/en/3.0.x/installation/).

## Acceptance Criteria
1. A new folder named `backend` is created.
2. A python virtual environment is initialized
3. A minimal flask application is created in the `backend` folder
4. The flask application should serve a single endpoint at `/healthz` that returns and empty body and status code `200`

**Comment by paulfiesel** [comment]
I went ahead and completed the Acceptance Criteria. What are my next steps?

**Comment by hansenreid** [comment]
Next step is to open a pull request with your changes and assign me as the reviewer.
