### ISSUE TITLE
Set up autoenv

### ISSUE THREAD

**Issue by hansenreid** [paulfiesel/TD2-Stats#2]
It can make development much easier to automatically activate python virtual environments. [autoenv](https://github.com/hyperupcall/autoenv) is a tool that can do this for you.

## Acceptance Criteria
1. Install autoenv
2. Verify when entering the `backend` directory that the virtual env is activated

**Comment by paulfiesel** [comment]
I am currently using Windows - considering getting a Linux-based laptop for this kind of work. My research shows **autoenv** is for MacOS/Linux primarily. Should we try to proceed, or use another tool like **direnv** as an alternative?

**Comment by paulfiesel** [comment]
I also found a VSCode extension that might work. 

VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=danielshow.autoenv

**Comment by paulfiesel** [comment]
Successfully setup venv and autoenv
