### ISSUE TITLE
Healthz integration test

### ISSUE THREAD

**Issue by hansenreid** [paulfiesel/TD2-Stats#3]
We want to add integration tests for every new endpoint we create. In #1 we added the `healthz` endpoint and now need a test for it. Documentation for testing flask applications can be found [here](https://flask.palletsprojects.com/en/3.0.x/testing/)

## Acceptance Criteria
1. Add an integration test that calls `/healthz`
2. Ensure the endpoint returns status code `200`
3. Ensure the body of the response is empty

**Comment by paulfiesel** [comment]
=== 1 passed in 2.31s ===

Test was successful. Also reviewed each line of test_healthz.py to understand each part of file.
